/*
 * API REST EXTERNA de DemoGenApp - Exemple de Servei Públic
 * Conjunt de Serveis REST de DemoGenApp per ser accedits públicament
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.apiexterna.client.exemplepublic.v1.api;

import org.fundaciobit.demogenapp.apiexterna.client.exemplepublic.v1.services.ApiException;
import org.fundaciobit.demogenapp.apiexterna.client.exemplepublic.v1.model.ExamplePojo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersioApi
 */
public class VersioApiTest {

    private final VersioApi api = new VersioApi();

    /**
     * Versio de l&#39;Aplicació
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versioTest() throws ApiException {
        //
        //String idioma = null;
        //
        //ExamplePojo response = api.versio(idioma);

        // TODO: test validations
    }
}
