/*
 * API REST INTERNA de DemoGenApp - Exemple de Servei Securitzat
 * Conjunt de Serveis REST de DemoGenApp per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.api.interna.client.exemplesecure.v1.api;

import org.fundaciobit.demogenapp.api.interna.client.exemplesecure.v1.services.ApiException;
import org.fundaciobit.demogenapp.api.interna.client.exemplesecure.v1.model.RestExceptionInfo;
import org.fundaciobit.demogenapp.api.interna.client.exemplesecure.v1.model.SendMessageResult;
import org.fundaciobit.demogenapp.api.interna.client.exemplesecure.v1.model.TipusDocumentalsPaginacio;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificacionsApi
 */
public class NotificacionsApiTest {

    private final NotificacionsApi api = new NotificacionsApi();

    /**
     * Retorna un llistat de tipus documentals
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callListTest() throws ApiException {
        //
        //Integer page = null;
        //
        //Integer pagesize = null;
        //
        //String language = null;
        //
        //TipusDocumentalsPaginacio response = api.callList(page, pagesize, language);

        // TODO: test validations
    }
    /**
     * Envia un missatge al mòbil del ciutada a traves de l&#39;App de Carpeta.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendNotificationToMobileTest() throws ApiException {
        //
        //List<String> notificationParameters = null;
        //
        //String langError = null;
        //
        //SendMessageResult response = api.sendNotificationToMobile(notificationParameters, langError);

        // TODO: test validations
    }
}
