/*
 * API REST INTERNA de DemoGenApp
 * Conjunt de Serveis REST de DemoGenApp per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.apiinterna.client.api;

import org.fundaciobit.demogenapp.apiinterna.client.services.ApiException;
import org.fundaciobit.demogenapp.apiinterna.client.model.LlistaDeExempleInfoPaginada;
import org.fundaciobit.demogenapp.apiinterna.client.model.RestExceptionInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    /**
     * Retorna informació d&#39;exemple per Dades Obertes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultaTest() throws ApiException {
        //
        //String name = null;
        //
        //String startdate = null;
        //
        //String enddate = null;
        //
        //Integer page = null;
        //
        //Integer pageSize = null;
        //
        //String language = null;
        //
        //LlistaDeExempleInfoPaginada response = api.consulta(name, startdate, enddate, page, pageSize, language);

        // TODO: test validations
    }
}
