/*
 * API REST INTERNA de DemoGenApp
 * Conjunt de Serveis REST de DemoGenApp per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.apiinterna.client.api;

import org.fundaciobit.demogenapp.apiinterna.client.services.ApiException;
import org.fundaciobit.demogenapp.apiinterna.client.model.ExamplePojo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersiApi
 */
public class VersiApiTest {

    private final VersiApi api = new VersiApi();

    /**
     * Versio de l&#39;Aplicació
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versioTest() throws ApiException {
        //
        //String idioma = null;
        //
        //ExamplePojo response = api.versio(idioma);

        // TODO: test validations
    }
}
