/*
 * API REST EXTERNA de DemoGenApp - Exemple de Servei Securitzat
 * Conjunt de Serveis REST de DemoGenApp per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.apiexterna.client.exemplesecure.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConstantsWs
 */
@JsonPropertyOrder({
  ConstantsWs.JSON_PROPERTY_R_O_L_E_E_J_B_F_U_L_L_A_C_C_E_S_S,
  ConstantsWs.JSON_PROPERTY_R_O_L_E_E_J_B_B_A_S_I_C_A_C_C_E_S_S,
  ConstantsWs.JSON_PROPERTY_R_O_L_E_E_J_B_W_S_A_C_C_E_S_S
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ConstantsWs {
  public static final String JSON_PROPERTY_R_O_L_E_E_J_B_F_U_L_L_A_C_C_E_S_S = "ROLEEJBFULLACCESS";
  @javax.annotation.Nonnull
  private String ROLEEJBFULLACCESS = "Constants.ROLE_EJB_FULL _ ACCESS";

  public static final String JSON_PROPERTY_R_O_L_E_E_J_B_B_A_S_I_C_A_C_C_E_S_S = "ROLEEJBBASICACCESS";
  @javax.annotation.Nonnull
  private Integer ROLEEJBBASICACCESS;

  public static final String JSON_PROPERTY_R_O_L_E_E_J_B_W_S_A_C_C_E_S_S = "ROLEEJBWSACCESS";
  @javax.annotation.Nonnull
  private Integer ROLEEJBWSACCESS;

  public ConstantsWs() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ConstantsWs(
    @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_F_U_L_L_A_C_C_E_S_S) String ROLEEJBFULLACCESS, 
    @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_B_A_S_I_C_A_C_C_E_S_S) Integer ROLEEJBBASICACCESS, 
    @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_W_S_A_C_C_E_S_S) Integer ROLEEJBWSACCESS
  ) {
    this();
    this.ROLEEJBFULLACCESS = ROLEEJBFULLACCESS;
    this.ROLEEJBBASICACCESS = ROLEEJBBASICACCESS;
    this.ROLEEJBWSACCESS = ROLEEJBWSACCESS;
  }

  /**
   * Constant ROLE_EJB_FULL _ ACCESS
   * @return ROLEEJBFULLACCESS
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_F_U_L_L_A_C_C_E_S_S)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getROLEEJBFULLACCESS() {
    return ROLEEJBFULLACCESS;
  }



  /**
   * Constant ROLE_EJB_BASIC _ ACCESS
   * @return ROLEEJBBASICACCESS
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_B_A_S_I_C_A_C_C_E_S_S)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getROLEEJBBASICACCESS() {
    return ROLEEJBBASICACCESS;
  }



  /**
   * Constant ROLE_EJB_WS _ ACCESS
   * @return ROLEEJBWSACCESS
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_R_O_L_E_E_J_B_W_S_A_C_C_E_S_S)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getROLEEJBWSACCESS() {
    return ROLEEJBWSACCESS;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstantsWs constantsWs = (ConstantsWs) o;
    return Objects.equals(this.ROLEEJBFULLACCESS, constantsWs.ROLEEJBFULLACCESS) &&
        Objects.equals(this.ROLEEJBBASICACCESS, constantsWs.ROLEEJBBASICACCESS) &&
        Objects.equals(this.ROLEEJBWSACCESS, constantsWs.ROLEEJBWSACCESS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ROLEEJBFULLACCESS, ROLEEJBBASICACCESS, ROLEEJBWSACCESS);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstantsWs {\n");
    sb.append("    ROLEEJBFULLACCESS: ").append(toIndentedString(ROLEEJBFULLACCESS)).append("\n");
    sb.append("    ROLEEJBBASICACCESS: ").append(toIndentedString(ROLEEJBBASICACCESS)).append("\n");
    sb.append("    ROLEEJBWSACCESS: ").append(toIndentedString(ROLEEJBWSACCESS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

