/*
 * API REST EXTERNA de DemoGenApp - Exemple de Servei Securitzat
 * Conjunt de Serveis REST de DemoGenApp per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.demogenapp.apiexterna.client.exemplesecure.v1.api;

import org.fundaciobit.demogenapp.apiexterna.client.exemplesecure.v1.services.ApiException;
import org.fundaciobit.demogenapp.apiexterna.client.exemplesecure.v1.model.ConstantsWs;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExempleSeguritzatApi
 */
public class ExempleSeguritzatApiTest {

    private final ExempleSeguritzatApi api = new ExempleSeguritzatApi();

    /**
     * Fa un ECHO
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void echoTest() throws ApiException {
        //
        //String echoInput = null;
        //
        //String response = api.echo(echoInput);

        // TODO: test validations
    }
}
